// src/pages/employer/views/ReportsAnalyticsView.styles.js
import { NAVY, GOLD } from '../constants';

export default {
  container: { maxWidth: '1000px', margin: '0 auto' },
  loading: { textAlign: 'center', padding: '60px', color: '#94a3b8' },
  header: { display: 'flex', justifyContent: 'space-between', alignItems: 'flex-start', marginBottom: 24 },
  title: { margin: '0 0 4px 0', fontSize: 20, fontWeight: 800, color: NAVY },
  subtitle: { margin: 0, fontSize: 13, color: '#64748b' },
  exportBtn: {
    display: 'flex',
    alignItems: 'center',
    gap: 6,
    padding: '8px 14px',
    backgroundColor: '#ffffff',
    border: '1px solid #e2e8f0',
    borderRadius: '6px',
    fontSize: 12,
    fontWeight: 600,
  },
  card: {
    backgroundColor: '#ffffff',
    borderRadius: '10px',
    border: '1px solid #e2e8f0',
    overflow: 'hidden',
    marginBottom: 20,
    boxShadow: '0 1px 3px rgba(0,0,0,0.02)',
  },
  cardHeader: { padding: '16px 20px', borderBottom: '1px solid #e2e8f0' },
  cardTitle: { margin: 0, fontSize: 13, fontWeight: 700, color: NAVY },
  cardSubtitle: { margin: '0 0 20px 0', fontSize: 11, color: '#94a3b8' },
  emptyState: { padding: '32px', textAlign: 'center', color: '#94a3b8' },
  table: { width: '100%', borderCollapse: 'collapse', textAlign: 'left' },
  th: { padding: '10px 20px', fontSize: 10, fontWeight: 700, color: '#94a3b8', textTransform: 'uppercase' },
  tr: { borderBottom: '1px solid #f1f5f9' },
  td: { padding: '12px 20px', fontSize: 12, color: '#475569' },
  rankBadge: {
    width: 24,
    height: 24,
    borderRadius: '6px',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    fontSize: 11,
    fontWeight: 700,
  },
  jobTitle: { fontWeight: 600, color: '#1e293b', fontSize: 13 },
  topBadge: { fontSize: 10, color: GOLD, marginTop: 2, fontWeight: 600 },
  twoCol: { display: 'grid', gridTemplateColumns: '1.5fr 1fr', gap: 20 },
  funnelRow: { display: 'flex', alignItems: 'center', gap: 12 },
  funnelLabel: { width: 110, fontSize: 11, color: '#64748b', textAlign: 'right', fontWeight: 500 },
  funnelBarTrack: { flex: 1, backgroundColor: '#f1f5f9', borderRadius: '4px', height: 20, overflow: 'hidden' },
  funnelBarFill: { height: '100%' },
  funnelValue: { width: 30, fontSize: 11, fontWeight: 600, color: '#1e293b' },
  pieContainer: { width: 140, height: 140, borderRadius: '50%', display: 'flex', alignItems: 'center', justifyContent: 'center', marginBottom: 20 },
  pieCenter: { width: 90, height: 90, backgroundColor: '#ffffff', borderRadius: '50%' },
  pieLegend: { display: 'flex', flexWrap: 'wrap', gap: 12, justifyContent: 'center' },
  legendItem: { display: 'flex', alignItems: 'center', gap: 4, fontSize: 11, color: '#475569', fontWeight: 500 },
  legendDot: { width: 6, height: 6, borderRadius: '50%' },
};